"""initial migration

Revision ID: 0235808efc4c
Revises: 
Create Date: 2025-11-27 19:20:11.785993

"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0235808efc4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('autor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade_paginas', sa.Integer(), nullable=False),
    sa.Column('editora', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livroscompras',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('preco_pago', sa.Float(), nullable=False),
    sa.Column('quantidade_comprados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'livro_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livroscompras')
    op.drop_table('livros')
    op.drop_table('usuarios')
    op.drop_table('admins')
    # ### end Alembic commands ###
