"""migracao livros type_checking

Revision ID: 0b8b5683d373
Revises: cfaeea14fccf
Create Date: 2025-11-28 11:03:33.061303

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b8b5683d373'
down_revision: Union[str, Sequence[str], None] = 'cfaeea14fccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
