"""ajustei horario2

Revision ID: 29d9609e0b01
Revises: 7a90f0c83e3d
Create Date: 2025-11-28 17:57:49.009494

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29d9609e0b01'
down_revision: Union[str, Sequence[str], None] = '7a90f0c83e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
