"""ajustei horario

Revision ID: 7a90f0c83e3d
Revises: b5df1e92d44e
Create Date: 2025-11-28 17:56:39.205729

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a90f0c83e3d'
down_revision: Union[str, Sequence[str], None] = 'b5df1e92d44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
