"""ajuste livro

Revision ID: 7cf6a09d4c92
Revises: 29d9609e0b01
Create Date: 2025-11-29 23:27:27.645501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cf6a09d4c92'
down_revision: Union[str, Sequence[str], None] = '29d9609e0b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('preco_uni', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'preco_uni')
    # ### end Alembic commands ###
