"""migracao livros livro

Revision ID: b5df1e92d44e
Revises: dba5976e9d29
Create Date: 2025-11-28 11:15:01.488987

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5df1e92d44e'
down_revision: Union[str, Sequence[str], None] = 'dba5976e9d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
