"""migracao livros plural

Revision ID: cfaeea14fccf
Revises: 905d3291ca49
Create Date: 2025-11-28 11:01:22.326033

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfaeea14fccf'
down_revision: Union[str, Sequence[str], None] = '905d3291ca49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
