"""migracao livros type_checking2

Revision ID: dba5976e9d29
Revises: 0b8b5683d373
Create Date: 2025-11-28 11:11:02.065052

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dba5976e9d29'
down_revision: Union[str, Sequence[str], None] = '0b8b5683d373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
